services:
  database:
    image: "mysql:latest"
    environment:
      #user root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: "adminer:latest"
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DESIGN=pappu687
